name: Generate SBOM and Submit to Dependency Graph

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java and Gradle
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Replace with your project's Java version
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5 # Replace with the version compatible with your project

      # Step 3: Install CycloneDX Gradle Plugin
      - name: Add CycloneDX Gradle Plugin
        run: |
          echo "plugins { id 'org.cyclonedx.bom' version '1.7.4' }" >> build.gradle

      # Step 4: Generate the SBOM
      - name: Generate SBOM
        run: |
          ./gradlew cyclonedxBom
          ls build/reports/bom/ # Verify SBOM generation

      # Step 5: Upload SBOM as an artifact (optional)
      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: build/reports/bom/*.json

      # Step 6: Submit dependencies to GitHub Dependency Graph
      - name: Submit Dependencies
        uses: advanced-security/dependency-submission-action@v1
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          job-correlator: ${{ github.run_id }}
          manifest: build/reports/bom/bom.json
