name: Generate SBOM and Submit to Dependency Graph

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java and Gradle
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Replace with your project's Java version
          distribution: 'temurin'

      # Step 3: Analyze Gradle dependencies
      - name: Analyze Dependencies
        id: analyze-dependencies
        run: |
          ./gradlew dependencies --configuration runtimeClasspath > dependencies.txt

      # Step 4: Convert dependencies to a simple SBOM-like JSON file
      - name: Generate SBOM
        run: |
          echo '{ "dependencies": [' > sbom.json
          grep -E '\---|\\---' dependencies.txt | awk '{print "{\"name\": \"" $1 "\", \"version\": \"unknown\"},"}' >> sbom.json
          sed -i '$ s/,$//' sbom.json # Remove the trailing comma
          echo ']}' >> sbom.json
          cat sbom.json

      # Step 5: Upload the SBOM as an artifact (optional)
      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.json

      # Step 6: Submit dependencies to GitHub Dependency Graph
      - name: Submit Dependencies
        uses: advanced-security/dependency-submission-action@v1
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          job-correlator: ${{ github.run_id }}
          dependencies: sbom.json
